pipeline {
    agent any

    environment {
        // Define environment variables if needed
        REPO_NAME = 'testing'   
        BRANCH_NAME = 'main'              
    }

    triggers {
        // Trigger the pipeline when changes are pushed to the Git repository
        githubPush()  
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Set up Python Environment') {
            steps {
                script {
                    // Set up Python environment and install dependencies
                    // This installs virtualenv if not already present, creates a virtual environment,
                    // and installs dependencies from requirements.txt

                    sh 'python3 -m venv venv'      
                    sh '. venv/bin/activate && pip install --upgrade pip'  
                    sh '. venv/bin/activate && pip install -r requirements.txt' 
                }
            }
        }

        stage('Run Tests') {
            steps {
                script {
                    // Run tests using pytest or another testing tool
                    sh '. venv/bin/activate && pytest'  
                }
            }
        }

        stage('Deploy') {
            steps {
                script {
                    echo 'Deploying the application...'
                }
            }
        }
    }

    post {
        success {
            // Notify success (e.g, email)
            echo 'Pipeline completed successfully!'
        }
        failure {
            // Notify failure
            echo 'Pipeline failed.'
        }
    }
}
